/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**************************************************/
#include <stdint.h>
#include <FourDigitsLedDisplay.h>



#define BITLOW  0
#define BITHIGH 1

//#define LEDON   0
//#define LEDOFF  1

#define PIN_DATA 			2		//SDO
#define PIN_SHIFT_CLOCK 	1		//SCLK
#define PIN_STORAGE_CLOCK 	0		//LOAD


void init(void);
void simulate_once(uint8_t all_low_high);
void write_bit__(uint8_t low_high);
void write_shift_clock__(uint8_t low_high);
void write_storage_clock__(uint8_t low_high);
void delay(uint32_t);



// GPIOA_ODR = 0x40020000UL + 0x14UL. Pin0=0,1=1,2=2;
volatile uint32_t *pGPIOAOdr = (uint32_t *)(0x40020000UL + 0x14UL);
// GPIOA_BSRR = 0x40020000UL + 0x18UL; SET Pin0=0,1=1,2=2; RESET Pin0=bit16,1=17,2=18;
volatile uint32_t *pGPIOABSRR = (uint32_t *)(0x40020000UL + 0x18UL);


static GPIOToLedRegisterDefinition_t  *g_ledOutput;




int main(void)
{

	init();
    /* Loop forever */
	uint32_t i = 9999;
	for(;;)
	{
		gpiotoled_blast_uint(i);
		delay(500000);
		i--;
		if (i <= 0) i=9999;
	};
}







/**********************************************************************/
void init(void)
{
	// CLOCK
	// AHB1 = RCC_AHB1ENR, GPIOA EN = bit 1
	// RCC = 0x40020000UL + 0x3800UL; RCC_AHB1ENR (RCC AHB1 peripheral clock enable register) = RCC + 0x30
	volatile uint32_t *pRCCAhb1Enr = 	(uint32_t *)(0x40020000UL + 0x3800UL + 0x30UL);
	// RCC_AHB1ENR Enable GPIOA (bit 1)
	*pRCCAhb1Enr|=(1<<0);

	// GPIO = GPIOA = 0x40020000UL
	// mode = ouptup,  Output type = 0 Output push-pull, speed = 00: Low speed
	// GPIOA_MODER = 0x40020000UL + 0x00.  Val=01: General purpose output mode . Pin 0 = Bit [0,1] , Pin 1 = Bit [2,3] , Pin 3 = Bit [4,5]
	volatile uint32_t * pGPIOAModer = (uint32_t *)(0x40020000UL + 0x00UL);
	*pGPIOAModer &=  ~(0b000000); //clear first 6 for 0,1,2 pins
	*pGPIOAModer |=   (0b010101); //set 01 (output) for first 6 for 0,1,2 pins
	// GPIOA_OTYPER = 0x40020000UL + 0x04.. Val = 0: Output push-pull (reset state). Pin0=0,1=1,2=2;
	volatile uint32_t * pGPIOAOType = (uint32_t *)(0x40020000UL + 0x04UL);
	*pGPIOAOType &= ~(0b111); //clear
	*pGPIOAOType |=  (0b000); //set 0 (output) for pins 0,1,2 (bit 0,1,2)
	// GPIOx_PUPDR = 0x40020000UL + 0x0C.  PUPDR2[1:0] PUPDR1[1:0] PUPDR0[1:0]/ 01: Pull-up 10: Pull-down
	volatile uint32_t *pGPIOAPuPd = (uint32_t *)(0x40020000UL + 0x0CUL);
	*pGPIOAPuPd &= ~(0b111111); //clear
	*pGPIOAPuPd |= ~(0b010101); //set 01: Pull-up
	// GPIOA_ODR = 0x40020000UL + 0x14UL. Pin0=0,1=1,2=2;
	// GPIOA_BSRR = 0x40020000UL + 0x18UL; SET Pin0=0,1=1,2=2; RESET Pin0=bit16,1=17,2=18;

	// GPIOA_ODR = 0x40020000UL + 0x14UL. Pin0=0,1=1,2=2;
	//volatile uint32_t *pGPIOAOdr = (uint32_t *)(0x40020000UL + 0x14UL);

	// GPIOA_BSRR = 0x40020000UL + 0x18UL; SET Pin0=0,1=1,2=2; RESET Pin0=bit16,1=17,2=18;
	volatile uint32_t *pGPIOABSRR = (uint32_t *)(0x40020000UL + 0x18UL);
	g_ledOutput = gpiotoled_init();
	g_ledOutput->pGPIOABSRR = pGPIOABSRR;
	g_ledOutput->output_pin_data = PIN_DATA;
	g_ledOutput->output_pin_shift_clock = PIN_SHIFT_CLOCK;
	g_ledOutput->output_pin_storage_clock = PIN_STORAGE_CLOCK;
}

/*
 * **********************************************************************
 * Deprecated/ Replaced by FourDigitsLedDisplay.h
 *
 * *********************************************************************/
void write_pin___(uint8_t pin, uint8_t low_high)
{
	if      (low_high==BITLOW ){ *pGPIOABSRR |= (0b1 << (16 + pin));} // reset
	else if (low_high==BITHIGH){ *pGPIOABSRR |= (0b1 << (0  + pin));} // set
}

void write_bit__(uint8_t low_high)
{
	write_pin___(PIN_DATA , low_high);
}

void write_shift_clock__(uint8_t low_high)
{
	write_pin___(PIN_SHIFT_CLOCK , low_high);
}

void write_storage_clock__(uint8_t low_high)
{
	write_pin___(PIN_STORAGE_CLOCK , low_high);
}






/**********************************************************************/
void delay(uint32_t time)
{
	for (uint32_t i =0 ; i< time; i++);
}
