/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	uint32_t u32, u32s=0x2000000;
	u32 = u32s+1; //

	uint8_t *pu8, *pu8s=0x2000000;
	pu8 = pu8s + 1;  //0x2000001

	uint16_t *pu16, *pu16s=0x2000000;
	pu16 = pu16s + 1;//0x2000002

	uint32_t *pu32, *pu32s=0x2000000;
	pu32 = pu32s + 1;//0x2000004

    /* Loop forever */
	for(;;);
}
